version: "3"
services:
  javaspring-db:
    image: myjddocker/javaspring-db:V1
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=javaspringdbpass
  javaspringcache01:
    image: memcached
    ports:
      - "11211:11211"
  javaspringmq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  javaspringapp:
    image: myjddocker/javaspring-app:V1
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
  javaspringweb:
    image: myjddocker/javaspring-web:V1
    ports:
      - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {}
